Adds button to move plants from one plot to another
statonlab/AVIDWeb pull request #374
Opened 2020-12-16 22:24 UTC by noahcaldwell7

There are a few bugs to iron out still:

- [ ] Any associated measurements do not transfer over and are deleted. This is because the button uses preexisting functionality to create a new plant at the new plot, then deletes the original plant.
- [ ] User can select to move to the same plot. this doesn't break anything, but it probably shouldn't be an option.

2020-12-18 19:55 UTC, almasaeed2010 reviewed
PHP side looks good. @jwest60 can you check the JS and review the UI?

2020-12-18 19:55 UTC, almasaeed2010 commented on app/Http/Controllers/PlantController.php
> +
Need to verify that the user can update both the new plot before continuing. There is no need to check the site permissions since by checking the plot it automatically checks the site.

2020-12-18 20:40 UTC, jwest60 commented
JS side looks good but could you add a move plant button under the actions block on the plots page as well? (From the sidebar, go to My Data, then pick a site)

![image](https://user-images.githubusercontent.com/32902460/102659376-4b7e8b80-4147-11eb-9a87-475b4093ad4b.png)

2020-12-22 13:45 UTC, almasaeed2010 commented on app/Http/Controllers/PlantController.php
> +        $this->authorize('update', Plot::find($request->plot_id));
You need both authorize methods here sonce the action affects both the plant and the plot.
```suggestion
        $this->authorize('update', $plant);
        $this->authorize('update', Plot::find($request->plot_id));
```

You also need to validate before authorizing the plot since `Plot::find(...)` can return null if the plot is not found or if the request doesn't contain plot_id.

2020-12-22 13:48 UTC, almasaeed2010 requested changes
- [ ] Move plot authorization to be after validatation. Keep plant authorization at the top. (this concerns PlantController.php)
- [ ] I noticed that the `BetaPlantsView.vue` is formatted differently than Joe's and my format. This suggests that we share different config for this project. Let's try to match them up when can.

2021-07-08 14:29 UTC, merged