Test auth
statonlab/AVIDWeb pull request #408
Opened 2021-06-17 20:46 UTC by noahcaldwell7

Adds api controllers for tokens, sites, plots, plants, and measurements. There are no 'sync' functions yet that check whether app or server are more up-to-date yet, and no overwriting of server data with local app changes to existing data- this just uploads *new* sites, plots, plants, and measurements created in the app.

To-do:
- [ ] implement update functions to record edits made in the app
- [ ] implement sync functions

2021-06-30 22:30 UTC, noahcaldwell7 commented
Syncing with mobile app complete

2021-07-01 13:12 UTC, almasaeed2010 commented on app/Http/Controllers/Api/SitesController.php
> +        $sitesController = new SitesController();
Can't use `new SitesController()` on production environment as discussed on slack.

2021-07-01 13:12 UTC, almasaeed2010 commented on app/Http/Controllers/Api/SitesController.php
> +                $plotsController = new PlotsController();
Same thing here, we can't use `new PlotsController()`.

2021-07-01 13:15 UTC, almasaeed2010 commented on routes/api.php
>  });
Is this being used? If yes, extract to a controller. If no, please remove.

2021-07-01 13:20 UTC, almasaeed2010 commented on routes/api.php
> +Route::post('/upload/plot', [PlotsController::class, 'uploadPlot'])->middleware('auth:sanctum');
These seem to be named wrong? I couldn't a method named uploadPlot for example.

2021-07-01 13:29 UTC, noahcaldwell7 commented on routes/api.php
> +Route::post('/upload/plot', [PlotsController::class, 'uploadPlot'])->middleware('auth:sanctum');
I originally planned to have methods for updating the data of a single plot, plant, and measurement, but I was getting worried about running out of time for that before alpha release. So currently when an edit is made and pushed to the server, the server processes the whole site.

2021-07-01 13:30 UTC, noahcaldwell7 commented on routes/api.php
>  });
This is not being used, forgot to remove it after the initial testing phase.

2021-07-02 20:23 UTC, almasaeed2010 requested changes
Moving in the right direction. However, a few more issues to be resolved. As it stands, this code will create duplicates in the DB if validation fails at a deeper stager. For example, a user clicks upload on a site that has valid site and plot data but invalid plant data. In this case, the site and plot will be created in the DB and a validation error message is returned to the app. The user fixes the problem and submits again, a new site and plot will be created again since the app is not sending the IDs down to the app. We need a way to either rollback the transaction in case of a validation error or perform the entire validation at the top before adding anything to the DB.

2021-07-02 20:23 UTC, almasaeed2010 commented on app/Http/Controllers/Api/SitesController.php
> +                        Log::info($validator->errors());
A few Log::info calls that should be removed

2021-07-02 20:23 UTC, almasaeed2010 commented on app/Http/Controllers/Api/SitesController.php
> +                            $serverPlant = $plantsApi->upload($serverPlot, $plant, $user);
The `$plantsApi->upload($serverPlot, $plant, $user);` doesn't always return a plant. It also returns errors if the plant tag already exists. We need to handle that case.

2021-07-02 23:09 UTC, noahcaldwell7 commented
I separated validation into its own function, and merged the single site and multiple site upload functions.

2021-07-06 14:13 UTC, almasaeed2010 requested changes

2021-07-06 14:13 UTC, almasaeed2010 commented on app/Http/Controllers/Api/SitesController.php
> +            }
The duplication issue still remains since we don't rollback transactions. But since you've extracted validation to its own function, this can be fixed easily:

```suggestion
        $sitesApi = new SitesApi();
        
        foreach($sites as $site) {
            $validation = $this->validateSite($site);
            if ($validation != 'validated successfully') {
                return $validation;
            }
        }
        
        DB::beginTransaction();
        foreach ($sites as $site) {
```

By validating all sites first, we can return any errors before we even start adding anything to the database.

2021-07-06 14:13 UTC, almasaeed2010 commented on app/Http/Controllers/Api/SitesController.php
> +        DB::beginTransaction();
Moved the transaction a few lines below since we don't need it until we start doing DB operations. See comment bellow for a bit more info.
```suggestion
```

2021-07-06 14:20 UTC, merged