Adds aggregate wmu column and command
statonlab/AVIDWeb pull request #434
Opened 2022-03-11 16:43 UTC by noahcaldwell7

2022-03-18 21:10 UTC, noahcaldwell7 commented
Resolves #432 and #433, with the exception of filters by township (as I'm not sure we track that) or by year (need more detail from Kristi). Ready for review.

2022-03-21 13:15 UTC, almasaeed2010 commented on app/Http/Controllers/ReportController.php
> +            ->orderBy($request->order_by ?? 'aggregate_wmu', $request->order_dir ?? 'asc')
Looks like order_dir is not validated. You can either validate the input or use this strategy instead:
```suggestion
            ->orderBy($request->order_by ?? 'aggregate_wmu', $request->order_dir === 'asc' ? 'asc' : 'desc')
```
This helps fend off SQL injection and makes sure typos in JS won't completely break the page.

2022-03-21 13:16 UTC, almasaeed2010 commented on app/Http/Controllers/ReportController.php
> +            ->orderBy($request->order_by ?? 'name', $request->order_dir ?? 'asc')
validate order_dir.

2022-03-21 13:20 UTC, almasaeed2010 commented on app/Http/Controllers/SiteController.php
> +        return Storage::get("maps/results.geojson");
which layer is this? aggregate wmus or just wmus?

2022-03-21 13:28 UTC, almasaeed2010 commented on resources/js/components/Reports/ReportByAggregateWmu.vue
> +        if (!axios.isCancel()) {
As an improvement to error handling here we can check for status 422 and alert the user that there is an input error. This would help us debug reported issues faster too. I'd add something like this everywhere we could receive a validation error:

```js
if (!axios.isCancel()) {
  if(e.response && e.response.status === 422) {
    // TODO: import Errors from '../../forms/Errors'
    const errors = new Errors(e.response.data)
    this.$alert(errors.toArray().join(' ')
  } else {
    this.$alert('Unable to load sites. Please try refreshing the page or contact us.')
  }
  console.error(e)
}

2022-03-21 13:31 UTC, almasaeed2010 requested changes
Looks great! Mostly minor updates 👍

2022-03-21 14:25 UTC, noahcaldwell7 commented on app/Http/Controllers/ReportController.php
> +    ];
I was originally using it before we queried aggregate_wmus. After we switched to using a query, I left the array because I thought a future feature might make use of it.

2022-03-21 22:29 UTC, noahcaldwell7 commented
Ready for further review. I made the requested changes, fixed the maps page, added a tab in the Reports page for breakdown by Town, and added pagination and search to the Town and State reports.

2022-03-22 20:04 UTC, almasaeed2010 commented on app/Http/Controllers/ReportController.php
> +        $sites = \DB::table('sites')
```suggestion
        $sites =Site::query()
```

2022-03-23 14:17 UTC, merged